Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  
  # VM pour SecureBank
  config.vm.define "securebank-web" do |web|
    web.vm.network "private_network", ip: "192.168.56.40"

    web.vm.synced_folder "../ansible", "/home/vagrant/ansible"

    web.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      # Locales
      sudo locale-gen fr_FR.UTF-8
      sudo update-locale LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8
      echo "export LANG=fr_FR.UTF-8" | sudo tee -a /etc/profile
      echo "export LC_ALL=fr_FR.UTF-8" | sudo tee -a /etc/profile
    SHELL

    web.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/home/vagrant/ansible/main.yml"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
      }
    end
  end

  # VM pour la PKI CFSSL
  config.vm.define "pki-server" do |pki|
    pki.vm.network "private_network", ip: "192.168.56.41"

    pki.vm.synced_folder "../ansible", "/home/vagrant/ansible"

    pki.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      # Locales
      sudo locale-gen fr_FR.UTF-8
      sudo update-locale LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8
      echo "export LANG=fr_FR.UTF-8" | sudo tee -a /etc/profile
      echo "export LC_ALL=fr_FR.UTF-8" | sudo tee -a /etc/profile
    SHELL

    pki.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/home/vagrant/ansible/pki_main.yml"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
      }
    end
  end
end
