services:
  securebank:
    build: ./src/SecureBank
    container_name: securebank
    depends_on:
      - mssql
      - maildev
      - storeapi
    environment: 
      - AppSettings:BaseUrl=https://securebank.com
      - AppSettings:StoreEndpoint:ApiUrl=https://securebank.com/api/Store/
      - AppSettings:StoreEndpoint:ApiToken=
      - AppSettings:SmtpCredentials:Ip=maildev
      - AppSettings:SmtpCredentials:Port=25
      - AppSettings:SmtpCredentials:Username=
      - AppSettings:SmtpCredentials:Password=
      - AppSettings:Ctf:Enabled=false
      - AppSettings:Ctf:Seed=example
      - AppSettings:Ctf:GenerateCtfdExport=false
      - AppSettings:Ctf:FlagFormat=ctf{{{0}}}
#      - AppSettings:Ctf:FlagFormat=ctf{{{0}}}.challenge{1}"
      - AppSettings:Ctf:UseRealChallengeName=true
      - AppSettings:Ctf:Challenges:SqlInjection=true
      - AppSettings:Ctf:Challenges:WeakPassword=true
      - AppSettings:Ctf:Challenges:SensitiveDataExposureStore=true
      - AppSettings:Ctf:Challenges:SensitiveDataExposureBalance=true
      - AppSettings:Ctf:Challenges:SensitiveDataExposureProfileImage=true
      - AppSettings:Ctf:Challenges:PathTraversal=true
      - AppSettings:Ctf:Challenges:Enumeration=true
      - AppSettings:Ctf:Challenges:XxeInjection=true
      - AppSettings:Ctf:Challenges:MissingAuthentication=true
      - AppSettings:Ctf:Challenges:RegistrationRoleSet=true
      - AppSettings:Ctf:Challenges:ChangeRoleInCookie=true
      - AppSettings:Ctf:Challenges:UnconfirmedLogin=true
      - AppSettings:Ctf:Challenges:ExceptionHandlingTransactionCreate=true
      - AppSettings:Ctf:Challenges:TableXss=true
      - AppSettings:Ctf:Challenges:PortalSearchXss=true
      - AppSettings:Ctf:Challenges:InvalidModelStore=true
      - AppSettings:Ctf:Challenges:InvalidModelTransaction=true
      - AppSettings:Ctf:Challenges:UnknownGeneration=true
      - AppSettings:Ctf:Challenges:HiddenPageRegisterAdmin=true
      - AppSettings:Ctf:Challenges:HiddenPageLoginAdmin=true
      - AppSettings:Ctf:Challenges:InvalidRedirect=true
      - AppSettings:Ctf:Challenges:DirectoryBrowsing=true
      - AppSettings:Ctf:Challenges:Swagger=true
      - AppSettings:Ctf:Challenges:Base2048Content=true
      - AppSettings:Ctf:Challenges:SimultaneousRequest=true
      - AppSettings:Ctf:Challenges:reDOS=true
      - AppSettings:Ctf:Challenges:FreeCredit=true
      - DatabaseConnections:SecureBankMSSQL:UserId=sa
      - DatabaseConnections:SecureBankMSSQL:UserPass=Your_Password123
      - DatabaseConnections:SecureBankMSSQL:Server=mssql
      - DatabaseConnections:SecureBankMSSQL:ServerPort=1433
      - DatabaseConnections:SecureBankMSSQL:Database=securebank
      - SeedingSettings:Seed=true
      - SeedingSettings:Admin=admin@ssrd.io
      - SeedingSettings:AdminPassword=admin
      - SeedingSettings:UserPassword=test1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./logs/securebank:/app/logs
    ports: 
      - 1337:80
  
  storeapi:
    build: ./src/StoreAPI
    container_name: storeapi
    depends_on: 
      - mssql
    environment: 
      - DatabaseConnections:StoreMSSQL:UserId=sa
      - DatabaseConnections:StoreMSSQL:UserPass=Your_Password123
      - DatabaseConnections:StoreMSSQL:Server=mssql
      - DatabaseConnections:StoreMSSQL:ServerPort=1433
      - DatabaseConnections:StoreMSSQL:Database=store
      - StoreAPI:Seed=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./logs/storeapi:/app/logs
    ports:
      - 1338:80
  
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment: 
      - ACCEPT_EULA=y
      - SA_PASSWORD=Your_Password123
    ports: 
      - 1433:1433
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mssql-data:/var/opt/mssql/backups
      - mssql-data:/var/opt/sqlserver
      - mssql-data:/var/opt/mssql

  mssql-secondary:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-secondary
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Your_Password123
    ports:
      - 1434:1433
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mssql-secondary-data:/var/opt/mssql
      - ./backups:/backups

  replication-agent:
    image: mcr.microsoft.com/mssql-tools
    container_name: replication-agent
    depends_on:
      - mssql
      - mssql-secondary
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./backups:/backups
    entrypoint: >
      /bin/bash -c "
        sleep 30 &&
        while true; do
          echo '[Replication] Backing up store and securebank...' &&
          /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Your_Password123 -Q \
            \"BACKUP DATABASE store TO DISK = '/backups/store.bak' WITH INIT\" &&
          /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Your_Password123 -Q \
            \"BACKUP DATABASE securebank TO DISK = '/backups/securebank.bak' WITH INIT\" &&

          echo '[Replication] Restoring on secondary...' &&
          /opt/mssql-tools/bin/sqlcmd -S mssql-secondary -U sa -P Your_Password123 -Q \
            \"RESTORE DATABASE store FROM DISK = '/backups/store.bak' WITH REPLACE, RECOVERY\" &&
          /opt/mssql-tools/bin/sqlcmd -S mssql-secondary -U sa -P Your_Password123 -Q \
            \"RESTORE DATABASE securebank FROM DISK = '/backups/securebank.bak' WITH REPLACE, RECOVERY\" &&
          sleep 30;
        done"

  maildev:
    image: maildev/maildev:1.1.0
    container_name: maildev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports: 
      - '127.0.0.1:1080:80'
      - '1025:25'

volumes:
  mssql-data:
  mssql-secondary-data:
