---
- name: Installer Docker sur Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer les paquets nécessaires
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Créer le dossier des keyrings Docker
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Télécharger la clé GPG officielle de Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: yes

    - name: Ajouter le dépôt Docker à APT
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ ansible_architecture | regex_replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        mode: '0644'

    - name: Recharger les sources APT
      apt:
        update_cache: yes

    - name: Installer Docker et ses composants
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
