---
- name: Installer et configurer HAProxy
  hosts: all
  become: true
  tasks:
    - name: Installer HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Créer le répertoire pour les certificats SSL
      file:
        path: /etc/haproxy/certs
        state: directory
        mode: '0755'

    - name: Générer un certificat auto-signé pour securebank.com
      shell: |
        openssl req -x509 -newkey rsa:2048 -keyout /etc/haproxy/certs/securebank.key -out /etc/haproxy/certs/securebank.crt -days 365 -nodes -subj "/C=FR/ST=France/L=City/O=SecureBank/CN=securebank.com"
        cat /etc/haproxy/certs/securebank.crt /etc/haproxy/certs/securebank.key > /etc/haproxy/certs/securebank.pem
      args:
        creates: /etc/haproxy/certs/securebank.pem

    - name: Configurer HAProxy avec headers de protection
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          global
              log /dev/log local0
              ssl-default-bind-ciphers PROFILE=SYSTEM
              ssl-default-bind-options no-sslv3 no-tls-tickets
              chroot /var/lib/haproxy
              stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
              stats timeout 30s
              user haproxy
              group haproxy
              daemon

          defaults
              log global
              mode http
              option httplog
              timeout connect 5000ms
              timeout client  50000ms
              timeout server  50000ms
              errorfile 400 /etc/haproxy/errors/400.http
              errorfile 403 /etc/haproxy/errors/403.http
              errorfile 408 /etc/haproxy/errors/408.http
              errorfile 500 /etc/haproxy/errors/500.http
              errorfile 502 /etc/haproxy/errors/502.http
              errorfile 503 /etc/haproxy/errors/503.http
              errorfile 504 /etc/haproxy/errors/504.http

          frontend http_front
              bind *:80
              # Redirection vers securebank.com si ce n'est pas déjà le cas
              redirect location https://securebank.com%[req.uri] code 301 if !{ hdr(host) -i securebank.com }
              # Redirection HTTP vers HTTPS pour securebank.com
              redirect scheme https code 301 if { hdr(host) -i securebank.com }

          frontend https_front
              bind *:443 ssl crt /etc/haproxy/certs/securebank.pem
              # Redirection vers securebank.com si ce n'est pas déjà le cas
              redirect location https://securebank.com%[req.uri] code 301 if !{ hdr(host) -i securebank.com }
              default_backend securebank_servers

              # Headers de protection
              http-response set-header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
              http-response set-header X-Frame-Options "DENY"
              http-response set-header X-Content-Type-Options "nosniff"
              http-response set-header X-XSS-Protection "1; mode=block"
              http-response set-header Referrer-Policy "no-referrer"
              http-response set-header Permissions-Policy "geolocation=(), microphone=(), camera=()"
              # Facultatif : à adapter selon ton app
              # http-response set-header Content-Security-Policy "default-src 'self'; object-src 'none'; frame-ancestors 'none';"

          backend securebank_servers
              balance roundrobin
              option httpchk GET /
              server securebank 127.0.0.1:1337 check
      notify:
        - Restart haproxy

  handlers:
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted 