---
- name: Lancer SecureBank avec Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Lancer docker-compose pour SecureBank
      shell: |
        docker compose -f docker-compose.yaml up -d
      args:
        chdir: "/home/vagrant/ansible/docker" 
